Repository OrmiBandi/DeVtail, pull requests merged in 2024-02, with the labels that each got.

#70 :bug: Fix: Tag 필터링 시 소개글과 제목을 같이 필터링하는 오류 발생
  studies/views.py
  templates/studies/study_detail.html
  templates/studies/study_list.html
Labels: bug

#71 :sparkles: Feat: 비밀번호 찾기 기능 개발
  accounts/tests.py
  accounts/urls.py
  accounts/views.py
  deVtail/settings.py
  templates/accounts/password_find.html
  templates/accounts/password_reset.html
  templates/accounts/password_reset_subject.txt
Labels: feature

#69 :sparkles: Feat: Studies 앱 Schedule 기능 개발
  studies/admin.py
  studies/forms.py
  studies/tests/study_tests.py
  studies/views.py
  templates/studies/study_detail.html
Labels: feature

#73 :sparkles: Feat: 스터디 ToDo 생성 기능 (#59)
  studies/models.py
  templates/todos/todo_detail.html
  templates/todos/todo_list.html
  todos/forms.py
  todos/tests/test_forms.py
  todos/tests/test_views.py
  todos/urls.py
  todos/views.py
Labels: feature

#76 Fix: Studies 앱 study_tests.py 파일 수정
  studies/tests/study_tests.py
Labels: bug

#79 :lipstick: Design: base.html 개발
  accounts/tests.py
  static/assets/css/base.css
  templates/base.html
  templates/index.html
Labels: feature

#77 :sparkles: Feat: 스터디 할 일 수정 (#74)
  templates/todos/todo_detail.html
  templates/todos/todo_list.html
  todos/forms.py
  todos/tests/test_forms.py
  todos/tests/test_views.py
  todos/urls.py
  todos/views.py
Labels: feature

#82 :sparkles: Feat: Studies앱 참조 링크 기능 개발
  studies/forms.py
  templates/studies/study_detail.html
Labels: feature

#84 :lipstick: Design: daisyUI 추가 및 footer 추가
  static/assets/css/base.css
  templates/base.html
Labels: enhancement

#86 :lipstick: Design: Nav Bar 개발
  accounts/tests.py
  accounts/urls.py
  accounts/views.py
  main/urls.py
  static/assets/css/base.css
  static/assets/images/logo.png
  static/assets/js/base.js
  templates/accounts/signup.html
  templates/base.html
Labels: feature

#89 :bug: Fix: 채팅방 입장 시 인증 불가 문제 해결 ( #81 )
  chats/admin.py
  chats/consumers.py
  deVtail/settings.py
  templates/chats/temp_direct_chat.html
  templates/devmates/devmate_list.html
Labels: feature

#90 :lipstick: Design: 로그인 페이지 개발
  accounts/forms.py
  accounts/tests.py
  accounts/views.py
  static/assets/js/login.js
  templates/accounts/login.html
  templates/accounts/signup.html
  templates/base.html
  templates/index.html
Labels: feature

#93 ✨ Feat: direct chat 메시지 전송 구현 및 채팅방 나가기 기능 구현 ( #68 )
  chats/consumers.py
  chats/views.py
  templates/chats/temp_direct_chat.html
  templates/devmates/devmate_list.html
Labels: feature

#94 :lipstick: Design: todo 페이지
  templates/todos/todo_board.html
  templates/todos/todo_calendar.html
  templates/todos/todo_confirm_delete.html
  templates/todos/todo_detail.html
  templates/todos/todo_form.html
  templates/todos/todo_list.html
  todos/forms.py
  todos/templatetags/__init__.py
  todos/templatetags/custom_filters.py
  todos/tests/test_views.py
  todos/views.py
Labels: enhancement

#97 :bug: Fix: 스터디 모델 내 리더 속성 및 ref_link 관련 설정 수정
  deVtail/settings.py
  static/assets/images/favorite_img.png
  studies/migrations/0006_alter_reflink_study.py
  studies/migrations/0007_alter_reflink_study.py
  studies/models.py
  studies/tests/study_tests.py
  studies/views.py
  templates/studies/study_detail.html
  templates/studies/study_list.html
Labels: bug

#102 :memo: Docs: requirements.txt 수정
  requirements.txt
Labels: bug, documentation

#99 :lipstick: Design: 계정 관련 UI 개발
  accounts/views.py
  deVtail/urls.py
  static/assets/css/profile.css
  templates/accounts/login.html
  templates/accounts/password_find.html
  templates/accounts/password_reset.html
  templates/accounts/profile.html
  templates/base.html
Labels: feature

#103 :sparkles: Feat: CICD 용 yml 파일 추가
  .github/workflows/django.yml
Labels: feature

#104 :lipstick: Design: 스터디 관련 UI 개발
  static/assets/images/favorite_img.png
  static/assets/images/favorite_img_unchecked.png
  static/assets/images/members_count_img.png
  studies/forms.py
  studies/migrations/0008_remove_study_current_member.py
  studies/models.py
  studies/views.py
  templates/studies/study_detail.html
  templates/studies/study_list.html
Labels: feature

#105 :bug: Fix: 스터디 가입 안한 상태의 스터디 todo 조회 (#100)
  static/assets/js/base.js
  templates/403.html
  templates/todos/todo_confirm_delete.html
  templates/todos/todo_form.html
  todos/tests/test_views.py
  todos/views.py
Labels: bug
