Repository OrmiBandi/DeVtail, pull requests merged in 2024-01, with the labels that each got.

#9 ✨ Feat: 회원가입(이메일) 기능 개발
  accounts/apps.py
  accounts/forms.py
  accounts/managers.py
  accounts/migrations/0002_alter_user_development_field.py
  accounts/migrations/0003_user_auth_code_user_content.py
  accounts/models.py
  accounts/tests.py
  accounts/tools.py
  accounts/urls.py
  accounts/views.py
  deVtail/settings.py
  requirements.txt
  static/assets/images/test.jpg
Labels: feature

#17 :sparkles: Feat: TODO 조회 기능 (#7, #16)
  accounts/urls.py
  accounts/views.py
  deVtail/urls.py
  templates/accounts/login.html
  templates/todos/todo_detail.html
  templates/todos/todo_list.html
  todos/admin.py
  todos/migrations/0002_alter_todo_options_alter_todo_alert_set_and_more.py
  todos/models.py
  todos/tests.py
  todos/tests/__init__.py
  todos/tests/test_models.py
  todos/tests/test_views.py
  todos/urls.py
  todos/views.py
Labels: feature

#19 :sparkles: Feat: 회원가입(GitHub) 기능 개발
  accounts/adapters.py
  accounts/admin.py
  accounts/forms.py
  accounts/tests.py
  accounts/urls.py
  accounts/views.py
  deVtail/settings.py
  requirements.txt
  templates/accounts/signup.html
Labels: feature

#13 ✨ Feat: Devmates 앱 CRUD 및 testcase 구현
  devmates/migrations/0002_remove_devmate_created_at.py
  devmates/models.py
  devmates/tests.py
  devmates/urls.py
  devmates/views.py
  templates/devmates/devmate_list.html
  templates/devmates/devmate_received_list.html
Labels: feature

#11 ✨ Feat: 스터디(댓글, 대댓글) 관련 기능 개발 #6
  requirements.txt
  studies/admin.py
  studies/comment_tests.py
  studies/factories.py
  studies/forms.py
  studies/migrations/0002_alter_study_thumbnail.py
  studies/migrations/0003_alter_study_thumbnail.py
  studies/migrations/0004_alter_study_thumbnail.py
  studies/migrations/0005_remove_study_topic_study_title.py
  studies/models.py
  studies/study_tests.py
  studies/tests.py
  studies/urls.py
  studies/views.py
  templates/studies/form.html
  templates/studies/study_detail.html
  templates/studies/study_list.html
Labels: feature

#20 :sparkles: Feat: 개인 TODO 생성 기능
  templates/todos/todo_form.html
  todos/forms.py
  todos/tests/test_forms.py
  todos/tests/test_views.py
  todos/urls.py
  todos/views.py
Labels: feature

#29 :sparkles: Feat: 개인 ToDo 수정 기능 (#23)
  templates/todos/todo_detail.html
  todos/tests/test_views.py
  todos/urls.py
  todos/views.py
Labels: feature

#30 :recycle: Refactor: devmates testcase 리팩터링 ( #27 )
  devmates/tests.py
Labels: enhancement

#31 :sparkles: Feat: 로그인 기능 개발
  accounts/backends.py
  accounts/forms.py
  accounts/tests.py
  accounts/urls.py
  accounts/views.py
  deVtail/settings.py
  main/tests.py
  main/urls.py
  main/views.py
  templates/index.html
Labels: feature

#26 Fix: Studies 앱 내의 forms.py 파일 필수 필드 누락 에러메세지 중복 로직 수정
  studies/forms.py
  studies/tests/study_tests.py
Labels: bug

#33 :sparkles: Feat: ToDo 삭제 기능 (#32)
  templates/todos/todo_confirm_delete.html
  todos/tests/test_views.py
  todos/urls.py
  todos/views.py
Labels: feature

#35 :sparkles: Feat: 로그아웃 기능 개발
  accounts/tests.py
  accounts/urls.py
  accounts/views.py
Labels: feature

#39 :sparkles: Feat: 사용자 프로필 조회 기능 개발
  accounts/tests.py
  accounts/urls.py
  accounts/views.py
  templates/accounts/profile.html
Labels: feature

#36 :sparkles: Feat: Studies 앱 댓글, 대댓글 테스트 코드 작성 #24
  studies/comment_tests.py
  studies/factories.py
  studies/forms.py
  studies/migrations/0005_remove_study_topic_study_title.py
  studies/study_tests.py
  studies/tests/comment_tests.py
  studies/tests/study_tests.py
Labels: feature

#43 :sparkles: Studies 앱 tag 기능 추가
  studies/forms.py
  studies/migrations/0005_remove_study_topic_study_tag_study_title_and_more.py
  studies/models.py
  studies/tests/study_tests.py
  studies/views.py
  templates/studies/study_detail.html
  templates/studies/study_list.html
Labels: feature

#44 :sparkles: Feat: 사용자 정보 수정 기능 개발
  accounts/forms.py
  accounts/tests.py
  accounts/urls.py
  accounts/views.py
  templates/accounts/account_update.html
Labels: feature

#45 ✨ Feat: django channels 설치 및 반영 ( #28 )
  chats/consumers.py
  chats/migrations/0002_alter_chatmessage_direct_chat_and_more.py
  chats/models.py
  chats/routing.py
  chats/views.py
  deVtail/asgi.py
  deVtail/settings.py
  requirements.txt
Labels: feature

#47 :recycle: Refactor: accounts test code 리팩토링
  accounts/forms.py
  accounts/tests.py
Labels: enhancement

#50 :bug: Fix: 회원 가입 시 프로필 이미지 필드에 오류가 발생하는 버그 수정
  accounts/views.py
Labels: bug

#48 :sparkles: Feat: Studies 앱 멤버 관리(가입, 멤버 추방, 리더 양도)
  studies/forms.py
  studies/urls.py
  studies/views.py
  templates/studies/approve_study_join.html
  templates/studies/manage_study_member.html
  templates/studies/study_detail.html
Labels: feature

#52 :sparkles: Feat: 회원 탈퇴 기능 개발
  accounts/forms.py
  accounts/tests.py
  accounts/urls.py
  accounts/views.py
  templates/accounts/account_delete.html
Labels: feature

#57 :sparkles: Feat: 비밀번호 변경 기능
  accounts/forms.py
  accounts/tests.py
  accounts/urls.py
  accounts/views.py
  templates/accounts/password_change.html
Labels: feature

#54 :sparkles: Feat: 스터디 ToDo 리스트 기능 (#38)
  templates/todos/todo_calendar.html
  templates/todos/todo_list.html
  todos/migrations/0002_alter_todo_alert_set_alter_todo_content_and_more.py
  todos/migrations/0002_alter_todo_options_alter_todo_alert_set_and_more.py
  todos/tests/test_views.py
  todos/urls.py
  todos/views.py
Labels: feature

#56 :sparkles: Feat: Studies 앱 블랙리스트 기능 개발
  studies/admin.py
  studies/forms.py
  studies/tests/blacklist_tests.py
  studies/tests/study_join_tests.py
  studies/urls.py
  studies/views.py
  templates/studies/blacklist_user_list.html
  templates/studies/manage_study_member.html
  templates/studies/study_detail.html
Labels: feature

#62 :bug: Fix: Studies 앱 스터디 생성 시 Studymemeber 지정 오류
  studies/views.py
Labels: bug

#66 :sparkles: Feat: 1:1채팅방 생성 및 입장 구현 ( #65 )
  chats/consumers.py
  chats/routing.py
  chats/urls.py
  chats/views.py
  deVtail/asgi.py
  deVtail/settings.py
  requirements.txt
  templates/chats/temp_direct_chat.html
  templates/devmates/devmate_list.html
Labels: feature
